# Generated by Django 3.0.3 on 2020-05-23 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_taggit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='taggit',
            new_name='tags',
        ),
    ]
